apiVersion: v1
kind: Pod
metadata:
  name: producer
spec:
  containers:
  - name: producer
    image: {{ .Values.registry }}/argocd-practice/producer:1.0.1
    imagePullPolicy: Always
    env:
    - name: RABBITMQ_SERVICE_HOST
      value: {{ .Release.Namespace }}-rabbitmq

    - name: RABBITMQ_AUTH_USERNAME
      value: user

    - name: RABBITMQ_AUTH_PASSWORD
      valueFrom:
        secretKeyRef:
          name: {{ .Release.Namespace }}-rabbitmq
          key: rabbitmq-password