apiVersion: v2
name: rabbit
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: rabbitmq
    version: 12.0.8
    repository: oci://registry-1.docker.io/bitnamicharts
